BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_press: app.handle_clear()
        font_size: 80
    TextInput:
        id: input_name
        text: ''
        font_size: 80
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        font_size: 80
    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)
        font_size: 80